language: r
sudo: required
cache: packages

warnings_are_errors: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgdal1h
  - sudo apt-get -y install libgdal1-dev
  - sudo apt-get install libproj-dev
  - sudo apt-get install gdal-bin
  
before_script:
  - git config --global user.name "travis"
  - git config --global user.email "travis@example.org"
  
r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
