language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_binary_packages:
  - rgdal

r_github_packages:
  - rstudio/rmarkdown
  - jimhester/covr
  - jimhester/lintr

script:
  - R CMD build .
  - travis_wait 30 R CMD check *.tar.gz

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
