language: r
sudo: required
dist: trusty
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_binary_packages:
  - rgdal

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
